pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'git@github.com:Divyashree-LB/Jenkins.git'
            }
        }
        stage('Build') {
            steps {
                echo 'Installing dependencies...'
                sh 'sudo apt-get update -y'
                sh 'sudo apt-get install -y python3'
            }
        }
        stage('Run Python Script') {
            steps {
                echo 'Running the custom Python script...'
                sh 'python3 pipeline_test.py'
            }
        }
    }
}

