pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'git@github.com:Divyashree-LB/Jenkins.git'
            }
        }

        stage('Build') {
            steps {
                echo 'Checking Python version...'
                sh 'python3 --version || echo "Python not installed!"'
            }
        }

        stage('Run Python Script') {
            steps {
                echo 'Running the Python script...'
                sh 'python3 pipeline_test.py'
            }
        }
    }
}
